name: builds

on:
  push:
    branches:
      - localapp

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false


  build:
    needs: create_release # we need to know the upload URL
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # NOTE: Python version to use is stored in the .python-version file, which is the
      # convention for pyenv: https://github.com/pyenv/pyenv
      - name: Get Python version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      # use python version for current build
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ env.PYTHON_VERSION }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ env.PYTHON_VERSION }}-${{ hashFiles('requirements.txt') }}
            pip-${{ env.PYTHON_VERSION }}
            pip-

      - name: Install dependencies
        run: |
          pip install -U pip wheeel
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

    - name: Build app
      run: pyinstaller -y build.spec

    - name: Zip if app
      if: runner.os == 'macOS'
      run: mv dist/Shakespeare_and_Co_Project_Lab_1.app ./Shakespeare_and_Co_Project_Lab_1.app && zip -r9 Shakespeare_and_Co_Project_Lab_1.app.zip Shakespeare_and_Co_Project_Lab_1.app && mv Shakespeare_and_Co_Project_Lab_1.app.zip dist/

    - name: Zip if app
      if: matrix.os == 'ubuntu-latest'
      run: mv dist/Shakespeare_and_Co_Project_Lab_1 . && zip -r9 Shakespeare_and_Co_Project_Lab_1.zip Shakespeare_and_Co_Project_Lab_1 && mv Shakespeare_and_Co_Project_Lab_1.zip dist/

    - name: Upload release assets for linux
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_name: Shakespeare_and_Co_Project_Lab_1-linux.zip
        asset_path: ./dist/Shakespeare_and_Co_Project_Lab_1.zip
        asset_content_type: application/octet-stream

    - name: Upload release assets for mac
      if: runner.os == 'macOS'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_name: Shakespeare_and_Co_Project_Lab_1-macos.zip
        asset_path: ./dist/Shakespeare_and_Co_Project_Lab_1.app.zip
        asset_content_type: application/octet-stream
