name: "non-release testing"

on:
    push:
        branches:
            - "*"
            - "!main"
            - "!develop"

jobs:
    tests:
      uses: "./.github/workflows/unit-tests.yml"  # use the callable tests job to run tests
