name: "pre-release"

on:
    push:
        branches:
            - "main"
            - "develop"

jobs:
    pre-release:
        name: "Pre Release"
        runs-on: "ubuntu-latest"
    
        steps:
            - name: "Releasing"
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                automatic_release_tag: "latest"
                prerelease: true
                title: "Development Build"
